### ISSUE TITLE
"SyntaxError: Unexpected token export" in browsers in ostrio_flow-router-title.js

### ISSUE THREAD

**Issue by Kshatra** [VeliovGroup/Meteor-flow-router-title#7]
Line 133 in ostrio_flow-router-title.js

export { FlowRouterTitle };

 causes "SyntaxError: Unexpected token export" error on client side (FF 29, Chrome 55.0.2883.75):

**Comment by bstocks** [comment]
I'm also seeing this on Mac Chrome 55.0.2883.75 (64-bit)

**Comment by dr-dimitru** [comment]
Hi @Kshatra @bstocks does `ecmascript` package is installed on your en?

**Comment by bstocks** [comment]
yes ecmascript@0.6.1

**Comment by Kshatra** [comment]
yes, ecmascript is installed

**Comment by dr-dimitru** [comment]
Going to test it on my end. I'm just wondering how it passed through the meteor-build... Is there any errors at Server console?

**Comment by dr-dimitru** [comment]
Tested on my end, can't reproduce. Anyways I'll publish update today, with minor changes. Let me know if it will help.

**Comment by dr-dimitru** [comment]
Hi @Kshatra , @bstocks 

Please see [v1.2.5](https://github.com/VeliovGroup/Meteor-flow-router-title/releases/tag/2.1.5)

Let me know it is fixed on your end

**Comment by bstocks** [comment]
@dr-dimitru 

I've tried your latest version 2.1.6 and I'm still crashing, but now it's crashing in the build process.
Here is what happens when I try to run after installing the package:

```
=> Started proxy.
=> Errors prevented startup:

   While processing files with coffeescript (for target web.browser):
   packages/ostrio:flow-router-title/flow-router-title.coffee:1:1: reserved word 'export'

=> Your application has errors. Waiting for file change.
```

**Comment by dr-dimitru** [comment]
Hi @bstocks ,

What Meteor version?
Post contents of `.meteor/packages` file
